name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --release --examples --target=thumbv7em-none-eabi
    - name: Run tests
      run: cargo test --verbose
